### ISSUE TITLE
Fix https

### ISSUE THREAD

**Issue by dlublin** [Vidvox/hapvideosite#3]
Fix the DNS stuff so that https can be enabled.

**Comment by jackturner** [comment]
To do it on github, update the DNS records, hap.video should have four A records that point to these four IP addresses:
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

Then just delete and recreate the CNAME file in the repo and the option to use HTTPS should appear on https://github.com/Vidvox/hapvideosite/settings
