### ISSUE TITLE
Add ofxDSHapVideoPlayer to list of integrations / developers

### ISSUE THREAD

**Issue by dlublin** [Vidvox/hapvideosite#7]
A Direct Show implementation of HAP for OpenFrameworks can be found here:
https://github.com/secondstory/ofxDSHapVideoPlayer

It should be added to list of integrations / developers using the OpenFrameworks logo.

**Comment by jackturner** [comment]
Added to /developers:
![image](https://user-images.githubusercontent.com/15309/43467516-d2506ada-94af-11e8-9fd0-ee8d56513777.png)

**Comment by jackturner** [comment]
Added to /integrations:
![image](https://user-images.githubusercontent.com/15309/43467622-187a5b92-94b0-11e8-8d79-9efbf4503220.png)
